Lesson 12
Yulia0808/it-academy-java-core pull request #12
Opened 2022-11-10 13:52 UTC by Yulia0808

2022-11-14 09:59 UTC, Xini1 requested changes
Добавить второе задание

2022-11-14 09:59 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/task1/Write.java
> +        ;
лишняя точка с запятой

2022-11-14 09:59 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/task1/Write.java
> +        fileWriter(cubes);
возможно название writeToFile больше подошло бы

2022-11-14 09:59 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/task1/Write.java
> +            return newList;
отступ слишком сильный

2022-11-14 09:59 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/task1/output.txt
> +27
Файл с результатом не нужно коммитить, потому что он может быть сгенерирован заного

2022-11-14 09:59 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/task2/Game.java
> +
пусто :(

2022-11-15 09:46 UTC, Yulia0808 commented
> Добавить второе задание

я не могу его сделать.. раз 100 переписывала.. отдельные большие "шаги " знаю как делать, а вот соединить все вместе не получается.  Прошу сделать разбор этого задания на следующем уроке.

2022-11-23 16:06 UTC, Xini1 commented
Мы посмотрели на занятии, как можно было реализовать второе задание. Этот ПР я тогда закрываю с оценкой 6

2022-11-23 16:06 UTC, merged