Lesson 5
Yulia0808/it-academy-java-core pull request #7
Opened 2022-09-29 09:14 UTC by Yulia0808

2022-09-29 09:24 UTC, Xini1 requested changes

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task1.java
> +class Whistle {
В java принято иметь один класс верхнего уровня на файл. Либо перенеси main метод в класс Whistle и оставь его в собственном файле Whistle.java, либо Whistle в отдельном файле, main класс с main методом в отдельном (Task1.java / Main.java)

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task2.java
> +    public static class PaymentCard {
У тебя класс PaymentCard получился вложенным в Task2. Убери Task2, пусть останется только класс PaymentCard в файле PaymentCard.java

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task2.java
> +        double balance;
лучше делать переменные private

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task2.java
> +            if (balance - 2.6 > 0)
не забывай ставить скобочки { }

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task2.java
> +            System.out.println("check balance: " + paymentCard.toString());
здесь toString() вызывать необязательно. Когда ты к строке лепишь объект с мопощью "+", он toString() вызывается неявно

2022-09-29 09:24 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/Task2.java
> +           paymentCard.eatAffordably();
выравнивание

2022-09-29 18:44 UTC, Xini1 requested changes
В ПР попали классы из 6 домашнего

2022-09-29 18:44 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/PaymentCard.java
> +        if (balance - 2.6 > 0)
В трёх методах if без скобочек { }

2022-09-29 18:58 UTC, Yulia0808 commented on src/main/java/by/it_academy/lesson5/PaymentCard.java
> +        if (balance - 2.6 > 0)
Если убираю скобочки {} , то выдает ошибку.
Что теперь делать с 6 веткой?

2022-09-29 19:06 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/PaymentCard.java
> +        if (balance - 2.6 > 0)
Я имел ввиду поставь скобочки
if (balance - 4.6 > 0){
            balance -= 4.6;
}

2022-09-29 19:07 UTC, Xini1 commented on src/main/java/by/it_academy/lesson5/PaymentCard.java
> +        if (balance - 2.6 > 0)
Убери лишние файлы из этого ПР. Только по пятой оставь. Я в телеграмме писал уже тебе, как можно удалить файли из git не удаляя их физически

2022-10-05 08:07 UTC, Xini1 commented
Я переименовал пакеты в соответствии с номера лекций. И поправил скобки: принято писать открывающую скобку на той же строке что и if, закрывающую скобку - на новой строке, после кода.

В целом - хорошо, 9

2022-10-05 08:08 UTC, merged