Lesson 8
Yulia0808/it-academy-java-core pull request #9
Opened 2022-10-17 15:36 UTC by Yulia0808

2022-10-18 19:45 UTC, Xini1 requested changes
Все смешалось в кучу + class файлы

2022-10-18 19:45 UTC, Xini1 commented on src/main/java/by/it_academy/lesson8/task1/Animal.java
> +    private final String animal;
Мы вроде сошлись на том, что это имя

2022-10-18 19:45 UTC, Xini1 commented on src/main/java/by/it_academy/lesson8/taskFirst/AnimalHouse.java
> +public class AnimalHouse<T extends Animals> {
Дубликат?

2022-10-18 19:48 UTC, Yulia0808 commented on src/main/java/by/it_academy/lesson8/taskFirst/AnimalHouse.java
> +public class AnimalHouse<T extends Animals> {
возможно)

2022-10-18 19:50 UTC, Yulia0808 commented on src/main/java/by/it_academy/lesson8/task1/Animal.java
> +    private final String animal;
почему-то вчера у меня не добавились твои изменения и я молодец все сделала без них и лишнее удалила..

2022-10-18 20:09 UTC, Yulia0808 commented on src/main/java/by/it_academy/lesson8/task1/Animal.java
> +    private final String animal;
это все возможно исправить?

2022-10-20 15:43 UTC, Xini1 commented
8

2022-10-20 15:44 UTC, merged